import { ProductService } from 'src/app/services/product.service';
export const HOME = 'home';
export const CART = 'cart';
export const LOGIN = 'login';
export const SIGNIN = 'signin';
export const MY_ACCOUNT = 'my-account';
export const PRODUCTS = 'products';
export const PRODUCT = PRODUCTS + '/:id';
export const ABOUT_US = 'about-us';
export const NOT_FOUND = '**';
